apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-nginx
  namespace: argo-nginx
  labels:
    app: nginx
    updated: "#{Updated}"
spec:
  replicas: #{Replicas}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.20.0
          ports:
            - containerPort: 80


